// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using PersonalDataManagementSystem.BackendClient.Api.Authentication.Login;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace PersonalDataManagementSystem.BackendClient.Api.Authentication
{
    /// <summary>
    /// Builds and executes requests for operations under \api\Authentication
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AuthenticationRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The login property</summary>
        public global::PersonalDataManagementSystem.BackendClient.Api.Authentication.Login.LoginRequestBuilder Login
        {
            get => new global::PersonalDataManagementSystem.BackendClient.Api.Authentication.Login.LoginRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::PersonalDataManagementSystem.BackendClient.Api.Authentication.AuthenticationRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AuthenticationRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/Authentication", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::PersonalDataManagementSystem.BackendClient.Api.Authentication.AuthenticationRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AuthenticationRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/Authentication", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
